name: Sonarr
description: Smart PVR for newsgroup and bittorrent users
version: 4.0.16.2944-r0-1
slug: sonarr
url: https://github.com/selleronom/hassio-addons
arch:
  - aarch64
  - amd64
init: false
ports:
  8989/tcp: 8989
ports_description:
  8989/tcp: Web Interface (HTTP)
webui: http://[HOST]:[PORT:8989]
panel_icon: mdi:television-classic
map:
  - share:rw
  - media:rw
  - downloads:rw
