---
name: qBittorrent
version: "5.1.4-r1-10"
slug: qbittorrent
description: qBittorrent - A free and reliable P2P BitTorrent client
url: https://github.com/selleronom/hassio-addons/tree/main/qbittorrent
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: application
boot: auto
apparmor: true
ports:
  8080/tcp: null
  6881/tcp: null
  6881/udp: null
ports_description:
  8080/tcp: Web Interface (HTTP)
  6881/tcp: BitTorrent TCP
  6881/udp: BitTorrent UDP
webui: http://[HOST]:[PORT:8080]
ingress: false
ingress_port: 0
panel_icon: mdi:cloud-download
map:
  - share:rw
  - media:rw
