name: Radarr
description: Movie collection manager for Usenet and BitTorrent users
version: 5.16.3.9541-r0-1
slug: radarr
url: https://github.com/selleronom/hassio-addons
arch:
  - aarch64
  - amd64
init: false
ports:
  7878/tcp: 7878
ports_description:
  7878/tcp: Web Interface (HTTP)
webui: http://[HOST]:[PORT:7878]
panel_icon: mdi:filmstrip
map:
  - share:rw
  - media:rw
  - downloads:rw
