name: Caddy Home Assistant SSL proxy
slug: caddy_proxy
version: 2.10.2-r3-1
hassio_api: true
description: A reverse proxy using Caddy
arch:
  - aarch64
  - amd64
map:
  - ssl
  - share
init: false
ports:
  443/tcp: 443
options:
  domain: null
  certfile: public.crt
  keyfile: private.key
  trusted_proxies: null
schema:
  domain: str
  certfile: str
  keyfile: str
  trusted_proxies: str
