name: Cloudflared
description: Cloudflare Tunnel client for secure remote access
version: 2024.12.2-r0-1
slug: cloudflared
url: https://github.com/selleronom/hassio-addons
arch:
  - aarch64
  - amd64
init: false
hassio_api: true
ports:
  5053/tcp: null
ports_description:
  5053/tcp: Metrics port
webui: https://dash.cloudflare.com
panel_icon: mdi:cloud-lock
options:
  tunnel_token: ""
  tunnel_name: homeassistant
  metrics_port: 5053
  log_level: info
  protocol: auto
  no_tls_verify: false
schema:
  tunnel_token: password?
  tunnel_name: str?
  metrics_port: port?
  log_level: list(trace|debug|info|warn|error|fatal)?
  protocol: list(auto|quic|http2)?
  no_tls_verify: bool?
