name: Syncthing
version: 2.0.12-r0
slug: syncthing
description: Syncthing is a continuous file synchronization program in a decentralized way
url: https://github.com/selleronom/hassio-addons
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ingress: true
ingress_port: 8384
ingress_stream: true
host_network: true
panel_title: Syncthing
panel_icon: mdi:sync

# Use add-on private storage only; no host directories mapped by default
map: []

options:
  gui_user: "admin"
  gui_password: "changeme"
schema:
  gui_user: str
  gui_password: password
